name: Python testing
on:
  push:
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Download Repository
        uses: actions/checkout@v4
      - name: Install Python
        uses: actions/setup-python@v5
        with:
         python-version: '3.11'
      - name: Install packages
        run: pip install -r requirements.txt

      - name: Run tests
        run: pytest